[package]
name = "p_documenting"
version = "0.1.0"
edition = "2021"
description = "A test documenting"
license = "QuangCV"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
